
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

    <head>
        <title>SFML - Simple and Fast Multimedia Library</title>
        <meta name="author"             content="Laurent Gomila" />
        <meta name="copyright"          content="2007-2008" />
        <meta name="description"        content="SFML official website : tutorials, wiki, downloads, ..." />
        <meta name="keywords"           content="sfml,simple,fast,multimedia,library,c++,video,audio,input,opengl,window,windows,linux,object,oriented,api" />
        <meta name="language"           content="en" />
        <meta name="robots"             content="all" />
        <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
        <link rel="stylesheet" type="text/css"  href="http://sfml-dev.org/doxygen.css" title="default" media="screen,print" />
<link rel="stylesheet" type="text/css"  href="http://sfml-dev.org/tabs.css" title="default" media="screen,print" />
        <link rel="icon" type="image/ico" href="http://sfml-dev.org/images/favicon.ico"/>
        <link rel="alternate" type="application/rss+xml" title="RSS feed" href="http://sfml-dev.org/rss/news-en.xml" />
            </head>

    <body>

        <!-- Page title -->
        <div id="logo">
            <a href="http://sfml-dev.org/index.php" title="SFML home"><img src="http://sfml-dev.org/images/logo.jpg" width="770" height="200" class="link" title="SFML home" alt="SFML" /></a>
        </div>

        <!--- Container for menu + content, needed for correct page layout -->
        <div id="container">

            <!--- Navigation part -->
            <div id="navigation">

                <!-- Language -->
                
                <!-- Main menu -->
                <div id="main_menu">
                    <ul>
                        <li><a href="http://sfml-dev.org/index.php"  accesskey="1" title="Back to home page">Home</a></li>
                        <li><a href="http://sfml-dev.org/features.php"  accesskey="2" title="List of SFML features">Features</a></li>
                        <li><a href="http://sfml-dev.org/license.php"  accesskey="4" title="Details about the SFML license">License</a></li>
                        <li><a href="http://sfml-dev.org/download.php"  accesskey="5" title="Download SFML SDK">Download</a></li>
                        <li><a href="http://sfml-dev.org/tutorials/"  accesskey="3" title="Learn how to use SFML">Tutorials</a></li>
                        <li><a href="http://sfml-dev.org/documentation/"  accesskey="6" title="Browse the online documentation">Documentation</a></li>
                        <li><a href="http://en.sfml-dev.org/forums"                  accesskey="7" title="Go to the SFML help forums">Forum</a></li>
                        <li><a href="https://github.com/LaurentGomila/SFML/wiki"     accesskey="8" title="Explore the community wiki">Wiki</a></li>
                        <li><a href="https://github.com/LaurentGomila/SFML/issues"   accesskey="9" title="Browse development tasks">Tasks / bugs</a></li>
                        <li><a href="https://github.com/LaurentGomila/SFML"          accesskey="0" title="Project page on github">Github page</a></li>
                    </ul>
                </div>

                <!-- RSS feed -->
                <div id="rss_button" class="menu_button">
                    <a href="http://sfml-dev.org/rss/news-en.xml" title="Subscribe to SFML news">RSS 2.0</a>
                </div>

                <!-- Flattr button -->
                <div id="flattr_button" class="menu_button">
                    <script type="text/javascript">
                        var flattr_url = 'http://www.sfml-dev.org/';
                        var flattr_btn='compact';
                    </script>
                    <script src="http://api.flattr.com/button/load.js" type="text/javascript"></script>
                </div>

                <!-- Donation (PayPal) button -->
                <div id="donate_button" class="menu_button">
                    <form action="https://www.paypal.com/cgi-bin/webscr" method="post">
                       <input type="hidden" name="cmd" value="_s-xclick" />
                       <input type="hidden" name="hosted_button_id" value="PLG2ZLGFGGRYW" />
                       <input type="image" src="https://www.paypalobjects.com/WEBSCR-640-20110306-1/en_US/i/btn/btn_donate_SM.gif" name="submit" alt="PayPal - The safer, easier way to pay online!" />
                       <img alt="" src="https://www.paypalobjects.com/WEBSCR-640-20110306-1/fr_FR/i/scr/pixel.gif" width="1" height="1" />
                    </form>
                </div>

            </div>

            <!-- Page content -->
            <div id="content">
<!-- Generated by Doxygen 1.7.4 -->
<script type="text/javascript">
function hasClass(ele,cls) {
  return ele.className.match(new RegExp('(\\s|^)'+cls+'(\\s|$)'));
}

function addClass(ele,cls) {
  if (!this.hasClass(ele,cls)) ele.className += " "+cls;
}

function removeClass(ele,cls) {
  if (hasClass(ele,cls)) {
    var reg = new RegExp('(\\s|^)'+cls+'(\\s|$)');
    ele.className=ele.className.replace(reg,' ');
  }
}

function toggleVisibility(linkObj) {
 var base = linkObj.getAttribute('id');
 var summary = document.getElementById(base + '-summary');
 var content = document.getElementById(base + '-content');
 var trigger = document.getElementById(base + '-trigger');
 if ( hasClass(linkObj,'closed') ) {
   summary.style.display = 'none';
   content.style.display = 'block';
   trigger.src = 'open.png';
   removeClass(linkObj,'closed');
   addClass(linkObj,'opened');
 } else if ( hasClass(linkObj,'opened') ) {
   summary.style.display = 'block';
   content.style.display = 'none';
   trigger.src = 'closed.png';
   removeClass(linkObj,'opened');
   addClass(linkObj,'closed');
 }
 return false;
}
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<div class="header">
  <div class="headertitle">
<div class="title">Input.hpp</div>  </div>
</div>
<div class="contents">
<div class="fragment"><pre class="fragment"><a name="l00001"></a>00001 
<a name="l00002"></a>00002 <span class="comment">//</span>
<a name="l00003"></a>00003 <span class="comment">// SFML - Simple and Fast Multimedia Library</span>
<a name="l00004"></a>00004 <span class="comment">// Copyright (C) 2007-2009 Laurent Gomila (laurent.gom@gmail.com)</span>
<a name="l00005"></a>00005 <span class="comment">//</span>
<a name="l00006"></a>00006 <span class="comment">// This software is provided &#39;as-is&#39;, without any express or implied warranty.</span>
<a name="l00007"></a>00007 <span class="comment">// In no event will the authors be held liable for any damages arising from the use of this software.</span>
<a name="l00008"></a>00008 <span class="comment">//</span>
<a name="l00009"></a>00009 <span class="comment">// Permission is granted to anyone to use this software for any purpose,</span>
<a name="l00010"></a>00010 <span class="comment">// including commercial applications, and to alter it and redistribute it freely,</span>
<a name="l00011"></a>00011 <span class="comment">// subject to the following restrictions:</span>
<a name="l00012"></a>00012 <span class="comment">//</span>
<a name="l00013"></a>00013 <span class="comment">// 1. The origin of this software must not be misrepresented;</span>
<a name="l00014"></a>00014 <span class="comment">//    you must not claim that you wrote the original software.</span>
<a name="l00015"></a>00015 <span class="comment">//    If you use this software in a product, an acknowledgment</span>
<a name="l00016"></a>00016 <span class="comment">//    in the product documentation would be appreciated but is not required.</span>
<a name="l00017"></a>00017 <span class="comment">//</span>
<a name="l00018"></a>00018 <span class="comment">// 2. Altered source versions must be plainly marked as such,</span>
<a name="l00019"></a>00019 <span class="comment">//    and must not be misrepresented as being the original software.</span>
<a name="l00020"></a>00020 <span class="comment">//</span>
<a name="l00021"></a>00021 <span class="comment">// 3. This notice may not be removed or altered from any source distribution.</span>
<a name="l00022"></a>00022 <span class="comment">//</span>
<a name="l00024"></a>00024 <span class="comment"></span>
<a name="l00025"></a>00025 <span class="preprocessor">#ifndef SFML_INPUT_HPP</span>
<a name="l00026"></a>00026 <span class="preprocessor"></span><span class="preprocessor">#define SFML_INPUT_HPP</span>
<a name="l00027"></a>00027 <span class="preprocessor"></span>
<a name="l00029"></a>00029 <span class="comment">// Headers</span>
<a name="l00031"></a>00031 <span class="comment"></span><span class="preprocessor">#include &lt;SFML/Config.hpp&gt;</span>
<a name="l00032"></a>00032 <span class="preprocessor">#include &lt;SFML/System/NonCopyable.hpp&gt;</span>
<a name="l00033"></a>00033 <span class="preprocessor">#include &lt;SFML/Window/Event.hpp&gt;</span>
<a name="l00034"></a>00034 <span class="preprocessor">#include &lt;SFML/Window/WindowListener.hpp&gt;</span>
<a name="l00035"></a>00035 
<a name="l00036"></a>00036 
<a name="l00037"></a>00037 <span class="keyword">namespace </span>sf
<a name="l00038"></a>00038 {
<a name="l00044"></a><a class="code" href="classsf_1_1Input.php">00044</a> <span class="keyword">class </span>SFML_API <a class="code" href="classsf_1_1Input.php" title="Input handles real-time input from keyboard and mouse.">Input</a> : <span class="keyword">public</span> <a class="code" href="classsf_1_1WindowListener.php" title="Base class for classes that want to receive events from a window (for internal use only)...">WindowListener</a>, <a class="code" href="structsf_1_1NonCopyable.php" title="Utility base class to easily declare non-copyable classes.">NonCopyable</a>
<a name="l00045"></a>00045 {
<a name="l00046"></a>00046 <span class="keyword">public</span> :
<a name="l00047"></a>00047 
<a name="l00052"></a>00052     <a class="code" href="classsf_1_1Input.php" title="Input handles real-time input from keyboard and mouse.">Input</a>();
<a name="l00053"></a>00053 
<a name="l00062"></a>00062     <span class="keywordtype">bool</span> IsKeyDown(<a class="code" href="namespacesf_1_1Key.php#ad32ed01d3448273340bd25af5cdd9c81">Key::Code</a> KeyCode) <span class="keyword">const</span>;
<a name="l00063"></a>00063 
<a name="l00072"></a>00072     <span class="keywordtype">bool</span> IsMouseButtonDown(Mouse::Button Button) <span class="keyword">const</span>;
<a name="l00073"></a>00073 
<a name="l00083"></a>00083     <span class="keywordtype">bool</span> IsJoystickButtonDown(<span class="keywordtype">unsigned</span> <span class="keywordtype">int</span> JoyId, <span class="keywordtype">unsigned</span> <span class="keywordtype">int</span> Button) <span class="keyword">const</span>;
<a name="l00084"></a>00084 
<a name="l00091"></a>00091     <span class="keywordtype">int</span> GetMouseX() <span class="keyword">const</span>;
<a name="l00092"></a>00092 
<a name="l00099"></a>00099     <span class="keywordtype">int</span> GetMouseY() <span class="keyword">const</span>;
<a name="l00100"></a>00100 
<a name="l00110"></a>00110     <span class="keywordtype">float</span> GetJoystickAxis(<span class="keywordtype">unsigned</span> <span class="keywordtype">int</span> JoyId, Joy::Axis Axis) <span class="keyword">const</span>;
<a name="l00111"></a>00111 
<a name="l00112"></a>00112 <span class="keyword">private</span> :
<a name="l00113"></a>00113 
<a name="l00118"></a>00118     <span class="keyword">virtual</span> <span class="keywordtype">void</span> OnEvent(<span class="keyword">const</span> <a class="code" href="classsf_1_1Event.php" title="Event defines a system event and its parameters.">Event</a>&amp; EventReceived);
<a name="l00119"></a>00119 
<a name="l00124"></a>00124     <span class="keywordtype">void</span> ResetStates();
<a name="l00125"></a>00125 
<a name="l00127"></a>00127     <span class="comment">// Member data</span>
<a name="l00129"></a>00129 <span class="comment"></span>    <span class="keywordtype">bool</span>  myKeys[Key::Count];                              
<a name="l00130"></a>00130     <span class="keywordtype">bool</span>  myMouseButtons[Mouse::ButtonCount];              
<a name="l00131"></a>00131     <span class="keywordtype">int</span>   myMouseX;                                        
<a name="l00132"></a>00132     <span class="keywordtype">int</span>   myMouseY;                                        
<a name="l00133"></a>00133     <span class="keywordtype">bool</span>  myJoystickButtons[<a class="code" href="namespacesf_1_1Joy.php#abb37a72f42b3ef9841fcf8270d0ac881a668554c121c39f79eceb15f8b6631a9f" title="Total number of supported joysticks.">Joy::Count</a>][<a class="code" href="namespacesf_1_1Joy.php#abb37a72f42b3ef9841fcf8270d0ac881aa555e27e351d2052df5f4b7b6e6953bf" title="Total number of supported joystick buttons.">Joy::ButtonCount</a>]; 
<a name="l00134"></a>00134     <span class="keywordtype">float</span> myJoystickAxis[<a class="code" href="namespacesf_1_1Joy.php#abb37a72f42b3ef9841fcf8270d0ac881a668554c121c39f79eceb15f8b6631a9f" title="Total number of supported joysticks.">Joy::Count</a>][Joy::AxisCount];      
<a name="l00135"></a>00135 };
<a name="l00136"></a>00136 
<a name="l00137"></a>00137 } <span class="comment">// namespace sf</span>
<a name="l00138"></a>00138 
<a name="l00139"></a>00139 
<a name="l00140"></a>00140 <span class="preprocessor">#endif // SFML_INPUT_HPP</span>
</pre></div></div>
</div>

            </div>
        </div>

        <!-- Page footer -->
        <div id="footer">
            <p>
                &nbsp;::&nbsp; Copyright &copy; 2007-2011
                <a href="mailto:laurent@sfml-dev.org" title="Send an e-mail to Laurent Gomila">Laurent Gomila</a>,
                all rights reserved &nbsp;::&nbsp;
                Icons from the Vista-Inspirate free icons set by
                <a href="http://sa-ki.deviantart.com/" title="Visit Alexandre Moore's website">Alexandre Moore</a> &nbsp;::&nbsp;

                <!-- Website by <a href="mailto:laurent.gom@gmail.com" title="Contact Laurent Gomila">Laurent Gomila</a> &nbsp;::&nbsp;
                This page is valid <a href="http://validator.w3.org/check?uri=referer" title="Page is valid XHTML 1.1">XHTML 1.1</a>
                and <a href="http://jigsaw.w3.org/css-validator/check/referer" title="Page is valid CSS 2">CSS 2</a> &nbsp;::&nbsp;
                http://sa-ki.deviantart.com/-->
            </p>
        </div>

        <!-- Google analytics -->
        <script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
        </script>
        <script type="text/javascript">
            _uacct = "UA-1839559-1";
            urchinTracker();
        </script>

    </body>

</html>
